# Generated by Django 3.1.6 on 2021-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='activitydetail',
            table='activity_detail',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
